trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.14.3'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o  meetupcontroller.exe'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: |
    ls -R -l '$(System.DefaultWorkingDirectory)'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-test-acr'
    repository: 'DB1Controller'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'